// <auto-generated />
namespace Mimry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddMimWidthHeight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMimWidthHeight));
        
        string IMigrationMetadata.Id
        {
            get { return "201405222219081_AddMimWidthHeight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
